language: python
cache: pip
python:
    - '3.4'
    - '3.5'
    - '3.6'
    - 'nightly'
    - 'pypy3'
install:
    - pip install pipenv==2018.10.13 # Avoid https://github.com/pypa/pipenv/issues/3313
    - travis_retry pipenv install --dev --system
script:
    - make test
after_success:
    - coveralls
matrix:
    allow_failures:
        - python: nightly
notifications:
    irc:
        channels:
            - secure: "b3VwfrTnaS8x6zMY9uYl9UcRk80FGTlfHHT2/44IGG670OLeD4N4sRniVwj6jooV1hylhADvPgKGFtH1VK+Fnb1c25dmnscmyeM6/A4KgJeqh5kuEPBxkuUJiczrVICvggvA3QtNETJKj2xavYFbwELiOttqk2NOSvOiEbP9B98="
    on_failure: change
    on_success: change

# The irc channel is encrypted for apertium/streamparser, so build notifications from forks won't show up on the IRC channel
# Encrypt with:
# $ gem install --user-install travis
# $ ~/.gem/ruby/*/bin/travis encrypt -r apertium/streamparser 'irc.oftc.net#apertium'
